---

sudo: required

services:
  - docker

language: python
python:
  - "2.7"

before_install:
  - docker pull solita/ubuntu-systemd
  # - make bin/python

script:
  - make travis

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
