FROM ubuntu:16.04

# Install systemd -- See https://hub.docker.com/_/centos/
#RUN yum -y swap -- remove fakesystemd -- install systemd systemd-libs
#RUN yum -y update; yum clean all; \
#(cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
#rm -f /lib/systemd/system/multi-user.target.wants/*; \
#rm -f /etc/systemd/system/*.wants/*; \
#rm -f /lib/systemd/system/local-fs.target.wants/*; \
#rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
#rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
#rm -f /lib/systemd/system/basic.target.wants/*; \
#rm -f /lib/systemd/system/anaconda.target.wants/*;

# Install Ansible
RUN apt update
RUN apt -y install  openssh-server auditd  grub2
RUN apt -y install git ansible sudo


# Fix for Travis docker containers
RUN mkdir /var/log/audit; chmod 700 /var/log/audit;
RUN touch /etc/default/grub; touch /etc/audit/audit.rules; touch /boot/grub/grub.cfg;

# Disable requiretty
RUN sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/'  /etc/sudoers

# Install Ansible inventory file
RUN echo '[local]\nlocalhost ansible_connection=local' > /etc/ansible/hosts

VOLUME ["/sys/fs/cgroup", "/var/log/audit"]

CMD ["/sbin/init"]
